services:
  n8n:
    image: n8nio/n8n:latest
    container_name: n8n-dev
    restart: unless-stopped
    network_mode: host
    dns:
      - 8.8.8.8
      - 8.8.4.4
    extra_hosts:
      - "localhost:127.0.0.1"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./data:/home/node/.n8n
      - ../dist:/home/node/.n8n/custom/node_modules/n8n-nodes-1password
